version: '3.8'

services:
  frontend:
    build: ./frontend
    container_name: fitnation-frontend
    ports:
      - "8000:80"  
    depends_on:
      - backend
    restart: always
    volumes:
      - ./frontend:/usr/share/nginx/html
  backend:
    build: ./backend
    ports:
      - "8080:80"
    depends_on:
      - db
    restart: always

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: fitnation
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
